// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruretfzgoetshyjeqwhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cmV0Znpnb2V0c2h5amVxd2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTMyMTQsImV4cCI6MjA2MTM4OTIxNH0.Ep_sqfgzsqIPkksx0OgS1c32Z3_TmeW-oXQzzAVumjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);